services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bookmyslot-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - REDIS_URL=redis://redis:6379
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: bookmyslot-worker
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    container_name: bookmyslot-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
