FROM node:22-slim
WORKDIR /app

# Install dependencies first for better caching
COPY package.json package-lock.json ./
COPY prisma ./prisma/
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port for Next.js
EXPOSE 3000

# Start development server
CMD npx prisma generate && npm run dev
